language: java
jdk:
- openjdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...

- mvn clean install skipTests=true
